import type { Job, LinkedInProfile } from '../types/job';

export const DEFAULT_LINKEDIN_PROFILE: LinkedInProfile = {
  isConnected: true,
  name: 'Birendra Mahto',
  headline: 'Senior Full Stack Engineer | React, TypeScript, Node.js & AI Systems',
  email: 'birendra.mahto@linkedin.user',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  preferredRoles: ['Senior Full Stack Engineer', 'Staff Frontend Architect', 'AI Systems Developer', 'Tech Lead'],
  preferredLocations: ['All Locations', 'Remote', 'San Francisco, CA', 'Bengaluru, India', 'New York, NY'],
  connectedAt: Date.now() - 30 * 86400000,
};

export const INITIAL_NEW_OPENINGS: Job[] = [
  {
    id: 'open-1',
    company: 'Anthropic',
    title: 'Senior Frontend Engineer - AI Interfaces',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/9988776655',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '$195,000 - $245,000',
    easyApply: 'Yes',
    notes: 'Matched 98% with your LinkedIn profile skills (React, TS, LLM UI).',
    status: 'new_openings',
    location: 'San Francisco, CA, United States',
    jobPostedDate: '1 hour ago',
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 3600000,
    order: 0,
  },
  {
    id: 'open-2',
    company: 'Supabase',
    title: 'Staff Full Stack Developer',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/8877665544',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '$180,000 - $220,000',
    easyApply: 'Yes',
    notes: 'Remote worldwide. Matched React + PostgreSQL + Realtime stack.',
    status: 'new_openings',
    location: 'Remote Worldwide',
    jobPostedDate: '3 hours ago',
    createdAt: Date.now() - 10800000,
    updatedAt: Date.now() - 10800000,
    order: 1,
  },
  {
    id: 'open-3',
    company: 'Postman',
    title: 'Lead Frontend Engineer (API Client Team)',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/7766554433',
    resumeUsed: 'Frontend_Lead_Resume',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '₹40 - ₹55 LPA',
    easyApply: 'Yes',
    notes: 'Matched your profile in Bengaluru tech community.',
    status: 'new_openings',
    location: 'Bengaluru, Karnataka, India',
    jobPostedDate: '5 hours ago',
    createdAt: Date.now() - 18000000,
    updatedAt: Date.now() - 18000000,
    order: 2,
  },
  {
    id: 'open-4',
    company: 'Datadog',
    title: 'Senior Software Engineer - UI Performance',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/6655443322',
    resumeUsed: 'SDE_Resume_v3',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '$185,000 - $215,000',
    easyApply: 'No',
    notes: 'Matched profile for High Scale Web Apps.',
    status: 'new_openings',
    location: 'New York, NY, United States',
    jobPostedDate: '1 day ago',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    order: 3,
  },
  {
    id: 'open-5',
    company: 'Google',
    title: 'Staff Software Engineer - Cloud Systems',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/5544332200',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '$210,000 - $260,000',
    easyApply: 'Yes',
    notes: 'Matched Silicon Valley systems architecture profile.',
    status: 'new_openings',
    location: 'San Jose, CA, United States',
    jobPostedDate: '1 day ago',
    createdAt: Date.now() - 90000000,
    updatedAt: Date.now() - 90000000,
    order: 4,
  },
  {
    id: 'open-6',
    company: 'Microsoft',
    title: 'Principal Engineer - Azure Developer Platform',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/4433221188',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '$200,000 - $250,000',
    easyApply: 'Yes',
    notes: 'Matched Redmond cloud developer tooling stack.',
    status: 'new_openings',
    location: 'Seattle, WA, United States',
    jobPostedDate: '2 days ago',
    createdAt: Date.now() - 170000000,
    updatedAt: Date.now() - 170000000,
    order: 5,
  },
  {
    id: 'open-7',
    company: 'Razorpay',
    title: 'Principal Software Engineer - Core Checkout',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/3322110099',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '₹50 - ₹70 LPA',
    easyApply: 'Yes',
    notes: 'Matched payment architecture & high throughput backend experience.',
    status: 'new_openings',
    location: 'Bengaluru, Karnataka, India',
    jobPostedDate: '2 days ago',
    createdAt: Date.now() - 172800000,
    updatedAt: Date.now() - 172800000,
    order: 6,
  },
  {
    id: 'open-8',
    company: 'Swiggy',
    title: 'Senior Engineering Manager - Supply Chain',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/2211009988',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '₹45 - ₹60 LPA',
    easyApply: 'Yes',
    notes: 'Matched high volume logistics & microservices stack.',
    status: 'new_openings',
    location: 'Hyderabad, Telangana, India',
    jobPostedDate: '3 days ago',
    createdAt: Date.now() - 259200000,
    updatedAt: Date.now() - 259200000,
    order: 7,
  },
  {
    id: 'open-9',
    company: 'DeepMind UK',
    title: 'Senior Staff Frontend Architect - AI Safety',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/1100998877',
    resumeUsed: 'Frontend_Lead_Resume',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '£130,000 - £160,000',
    easyApply: 'Yes',
    notes: 'Matched London AI research UI engineering.',
    status: 'new_openings',
    location: 'London, United Kingdom',
    jobPostedDate: '3 days ago',
    createdAt: Date.now() - 260000000,
    updatedAt: Date.now() - 260000000,
    order: 8,
  },
  {
    id: 'open-10',
    company: 'Shopify',
    title: 'Staff Full Stack Developer - Merchant Admin',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/0099887766',
    resumeUsed: 'FullStack_Engineer_2026',
    dateApplied: new Date().toISOString().split('T')[0],
    salaryRange: '$165,000 - $205,000 CAD',
    easyApply: 'Yes',
    notes: 'Matched e-commerce platform & GraphQL frontend architecture.',
    status: 'new_openings',
    location: 'Toronto, ON, Canada',
    jobPostedDate: '4 days ago',
    createdAt: Date.now() - 345600000,
    updatedAt: Date.now() - 345600000,
    order: 9,
  },
];
